language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os:
  - linux
install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz
  - tar -xzvf cmake-3.21.1-linux-x86_64.tar.gz
  - cd cmake-3.21.1-linux-x86_64/bin
before_script:
  - cd ../../
  - mkdir build && cd build
script:
  - ./cmake-3.21.1-linux-x86_64/bin/cmake ..
  - make